## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, normalize
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_drop = application_df.drop(columns=['EIN'])
application_df_drop.head(2)

NAME APPLICATION_TYPE  AFFILIATION  \
0            BLUE KNIGHTS MOTORCYCLE CLUB              T10  Independent   
1  AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3  Independent   

  CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS INCOME_AMT  \
0          C1000    ProductDev   Association       1          0   
1          C2000  Preservation  Co-operative       1     1-9999   

  SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0                      N     5000              1  
1                      N   108590              1

In [3]:
# Determine the number of unique values in each column.
application_cat = application_df_drop.dtypes[application_df_drop.dtypes=="object"].index.tolist()
application_df_drop[application_cat].nunique()


NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df_drop["APPLICATION_TYPE"].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list(app_counts[app_counts < 500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df_drop['APPLICATION_TYPE'] = application_df_drop['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
# application_df_drop["APPLICATION_TYPE"] = application_df_drop['APPLICATION_TYPE'].value_counts()
application_df_drop["APPLICATION_TYPE"].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df_drop['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df_drop['CLASSIFICATION'] = application_df_drop['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df_drop['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
application_name_count= application_df_drop["NAME"].value_counts()
application_name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ... 
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
names_to_replace = list(application_name_count[application_name_count < 400].index)

# Replace in dataframe
for name in names_to_replace:
    application_df_drop['NAME'] = application_df_drop['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df_drop['NAME'].value_counts()

Other                                              30674
PARENT BOOSTER USA INC                              1260
TOPS CLUB INC                                        765
UNITED STATES BOWLING CONGRESS INC                   700
WASHINGTON STATE UNIVERSITY                          492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC      408
Name: NAME, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_drop = pd.get_dummies(application_df_drop)
application_df_drop.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  \
0       1     5000              1   
1       1   108590              1   
2       1     5000              0   
3       1     6692              1   
4       1   142590              1   

   NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC  NAME_Other  \
0                                                  0              1   
1                                                  0              1   
2                                                  0              1   
3                                                  0              1   
4                                                  0              1   

   NAME_PARENT BOOSTER USA INC  NAME_TOPS CLUB INC  \
0                            0                   0   
1                            0                   0   
2                            0                   0   
3                            0                   0   
4                            0                   0   

   NAME_UNITED STATES BOWLING CONGRESS INC  NAME_WASHINGTON STATE UNIVERSITY  \
0                                        0                                 0   
1                                        0                                 0   
2                                        0                                 0   
3                                        0                                 0   
4                                        0                                 0   

   APPLICATION_TYPE_Other  ...  INCOME_AMT_1-9999  INCOME_AMT_10000-24999  \
0                       0  ...                  0                       0   
1                       0  ...                  1                       0   
2                       0  ...                  0                       0   
3                       0  ...                  0                       1   
4                       0  ...                  0                       0   

   INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  \
0                         0                   0                 0   
1                         0                   0                 0   
2                         0                   0                 0   
3                         0                   0                 0   
4                         1                   0                 0   

   INCOME_AMT_25000-99999  INCOME_AMT_50M+  INCOME_AMT_5M-10M  \
0                       0                0                  0   
1                       0                0                  0   
2                       0                0                  0   
3                       0                0                  0   
4                       0                0                  0   

   SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y  
0                         1                         0  
1                         1                         0  
2                         1                         0  
3                         1                         0  
4                         1                         0  

[5 rows x 50 columns]

In [12]:
# Split our preprocessed data into our features and target arrays
x = application_df_drop.drop(columns=['IS_SUCCESSFUL']).values
y = application_df_drop['IS_SUCCESSFUL'].values

In [13]:
x[0]

array([   1, 5000,    0,    1,    0,    0,    0,    0,    0,    1,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0,    0,
          0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          1,    1,    0,    0,    0,    1,    0,    0,    0,    0,    0,
          0,    0,    0,    1,    0])

In [14]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [15]:
# split into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [16]:
x_train[0]

array([   1, 5000,    0,    0,    0,    1,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    1,    0,    0,    0,    1,    0,    0,    0,    0,    0,
          0,    0,    0,    1,    0])

In [17]:
x_test[0]

array([   1, 5000,    0,    1,    0,    0,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    0,    0,    1,    0,    0,
          0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    1,    1,    0,    0,    0,    0,    0,
          0,    0,    0,    1,    0])

In [18]:
# Create a StandardScaler instances
x_train_scaled = normalize(x_train, norm = "l1")
x_test_scaled = normalize(x_test, norm = "l1")
# Fit the StandardScaler
# x_scaler = scaler.fit(x_train)

# Scale the data
# x_train_scaled = x_scaler.transform(x_train)
# x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

[1.99640647e-04 9.98203234e-01 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.99640647e-04 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.99640647e-04
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.99640647e-04 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.99640647e-04 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.99640647e-04 0.00000000e+00 1.99640647e-04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.99640647e-04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.99640647e-04
 0.00000000e+00]


## Compile, Train and Evaluate the Model

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(x_train_scaled[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_1_nodes,
                          input_dim=num_input_features,
                          activation='relu')
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_2_nodes,

                          activation='relu')
)


# Output layer
nn.add(
    tf.keras.layers.Dense(units=1,

                          activation='sigmoid')
)

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 80)                4000      
                                                                 
 dense_1 (Dense)             (None, 30)                2430      
                                                                 
 dense_2 (Dense)             (None, 1)                 31        
                                                                 
Total params: 6461 (25.24 KB)
Trainable params: 6461 (25.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
#  Create a callback
import os
from tensorflow.keras.callbacks import ModelCheckpoint
# Define the checkpoint path and filenames
os.makedirs("checkpoints3/",exist_ok=True)
checkpoint_path = "checkpoints3/weights.{epoch:02d}.hdf5"
# Create a callback which saves the weights for every 5 epochs
cp_callback= ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True, period=5)

In [22]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100,callbacks=[cp_callback])

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5322
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5335
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6910 - accuracy: 0.5335
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6910 - accuracy: 0.5335
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6907 - accuracy: 0.5335
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6908 - accuracy: 0.5335
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6907 - accuracy: 0.5335
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6905 - accuracy: 0.5335
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6901 - accuracy: 0.5335
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6895 - accura

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5752 - accuracy: 0.7191 - 520ms/epoch - 2ms/step
Loss: 0.5751633048057556, Accuracy: 0.7190670371055603


In [24]:
# Export our model to HDF5 file
nn.save("alphabetsoup3h.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
