## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df_drop = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df_drop.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [12]:
# # Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# application_df_drop = application_df.drop(columns=['EIN', 'NAME'])
# application_df_drop.head(2)

In [13]:
# Determine the number of unique values in each column.
# application_cat = application_df_drop.dtypes[application_df_drop.dtypes=="object"].index.tolist()
# application_df_drop[application_cat].nunique()


In [14]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df_drop["APPLICATION_TYPE"].value_counts()
app_counts

In [15]:
# # Choose a cutoff value and create a list of application types to be replaced
# # use the variable name `application_types_to_replace`

# application_types_to_replace = list(app_counts[app_counts < 500].index)
# # Replace in dataframe
# for app in application_types_to_replace:
#     application_df_drop['APPLICATION_TYPE'] = application_df_drop['APPLICATION_TYPE'].replace(app,"Other")

# # Check to make sure binning was successful
# app_counts_df = application_df_drop['APPLICATION_TYPE'].value_counts()
# app_counts_df

In [16]:
# # Look at CLASSIFICATION value counts for binning
# class_counts = application_df_drop['CLASSIFICATION'].value_counts()
# class_counts

In [17]:
# # You may find it helpful to look at CLASSIFICATION value counts >1
# class_counts[class_counts > 1]

In [18]:
# # Choose a cutoff value and create a list of classifications to be replaced
# # use the variable name `classifications_to_replace`
# classifications_to_replace = list(class_counts[class_counts < 1000].index)

# # Replace in dataframe
# for cls in classifications_to_replace:
#     application_df_drop['CLASSIFICATION'] = application_df_drop['CLASSIFICATION'].replace(cls,"Other")

# # Check to make sure binning was successful
# application_df_drop['CLASSIFICATION'].value_counts()

In [19]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_drop = pd.get_dummies(application_df_drop)
application_df_drop.head()

EIN  STATUS  ASK_AMT  IS_SUCCESSFUL  \
0  10520599       1     5000              1   
1  10531628       1   108590              1   
2  10547893       1     5000              0   
3  10553066       1     6692              1   
4  10556103       1   142590              1   

   NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC  \
0                                                  0                
1                                                  0                
2                                                  0                
3                                                  0                
4                                                  0                

   NAME_100 BLACK MEN OF AMERICA  NAME_100 BLACK MEN OF MEMPHIS INC  \
0                              0                                  0   
1                              0                                  0   
2                              0                                  0   
3                              0                                  0   
4                              0                                  0   

   NAME_100 BLACK MEN OF WEST GEORGIA INC  NAME_1150 WEBSTER STREET INC  \
0                                       0                             0   
1                                       0                             0   
2                                       0                             0   
3                                       0                             0   
4                                       0                             0   

   NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   ...  INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0  ...                  0                       0                         0   
1  ...                  1                       0                         0   
2  ...                  0                       0                         0   
3  ...                  0                       1                         0   
4  ...                  0                       0                         1   

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0   
1                   0                 0                       0   
2                   0                 0                       0   
3                   0                 0                       0   
4                   0                 0                       0   

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1   
1                0                  0                         1   
2                0                  0                         1   
3                0                  0                         1   
4                0                  0                         1   

   SPECIAL_CONSIDERATIONS_Y  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  

[5 rows x 19686 columns]

In [20]:
# Split our preprocessed data into our features and target arrays
x = application_df_drop.drop(columns=['IS_SUCCESSFUL']).values
y = application_df_drop['IS_SUCCESSFUL'].values

In [21]:
x[0]

array([10520599,        1,     5000, ...,        0,        1,        0])

In [22]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [23]:
# split into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [24]:
x_train[0]

array([352579190,         1,      5000, ...,         0,         1,
               0])

In [25]:
x_test[0]

array([474743111,         1,      5000, ...,         0,         1,
               0])

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(x_train_scaled[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_1_nodes,
                          input_dim=num_input_features,
                          activation='relu')
)


# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_2_nodes,

                          activation='relu')
)


# Output layer
nn.add(
    tf.keras.layers.Dense(units=1,

                          activation='sigmoid')
)

# Check the structure of the model
nn.summary()

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#  Create a callback
import os
from tensorflow.keras.callbacks import ModelCheckpoint
# Define the checkpoint path and filenames
os.makedirs("checkpoints2/",exist_ok=True)
checkpoint_path = "checkpoints2/weights.{epoch:02d}.hdf5"
# Create a callback which saves the weights for every 5 epochs
cp_callback= ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True, period=5)

In [ ]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100,callbacks=[cp_callback])

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
nn.save("alphabetsoup2h.h5")