## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [98]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_drop = application_df.drop(columns=['EIN', 'NAME'])
application_df_drop.head(2)

APPLICATION_TYPE  AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  \
0              T10  Independent          C1000    ProductDev   Association   
1               T3  Independent          C2000  Preservation  Co-operative   

   STATUS INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0       1          0                      N     5000              1  
1       1     1-9999                      N   108590              1

In [99]:
# Determine the number of unique values in each column.
application_cat = application_df_drop.dtypes[application_df_drop.dtypes=="object"].index.tolist()
application_df_drop[application_cat].nunique()


APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [100]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df_drop["APPLICATION_TYPE"].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [101]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list(app_counts[app_counts < 500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df_drop['APPLICATION_TYPE'] = application_df_drop['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_counts_df = application_df_drop['APPLICATION_TYPE'].value_counts()
app_counts_df

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [102]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df_drop['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [103]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [104]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df_drop['CLASSIFICATION'] = application_df_drop['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df_drop['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [105]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_drop = pd.get_dummies(application_df_drop)
application_df_drop.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                       0   
1       1   108590              1                       0   
2       1     5000              0                       0   
3       1     6692              1                       0   
4       1   142590              1                       0   

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                     1                     0                    0   
1                     0                     0                    1   
2                     0                     0                    0   
3                     0                     0                    1   
4                     0                     0                    1   

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                    0                    0                    0  ...   
1                    0                    0                    0  ...   
2                    0                    1                    0  ...   
3                    0                    0                    0  ...   
4                    0                    0                    0  ...   

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                  0                       0                         0   
1                  1                       0                         0   
2                  0                       0                         0   
3                  0                       1                         0   
4                  0                       0                         1   

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0   
1                   0                 0                       0   
2                   0                 0                       0   
3                   0                 0                       0   
4                   0                 0                       0   

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1   
1                0                  0                         1   
2                0                  0                         1   
3                0                  0                         1   
4                0                  0                         1   

   SPECIAL_CONSIDERATIONS_Y  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  

[5 rows x 44 columns]

In [106]:
# Split our preprocessed data into our features and target arrays
x = application_df_drop.drop(columns=['IS_SUCCESSFUL']).values
y = application_df_drop['IS_SUCCESSFUL'].values

In [107]:
x[0]

array([   1, 5000,    0,    1,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,    1,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [108]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [111]:
# split into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [112]:
x_train[0]

array([   1, 5000,    0,    0,    0,    1,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
          0,    0,    0,    0,    1,    0,    1,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [113]:
x_test[0]

array([   1, 5000,    0,    0,    0,    1,    0,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    1,    0,    0,    0,    0,    1,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [114]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

[ 0.01079982 -0.02957055 -0.08940766 -0.12358845 -0.17846338  0.52028597
 -0.21848437 -0.18930918 -0.19399646 -0.14518018 -0.15039866  1.08034442
 -0.04278355 -1.07318949 -0.03118975 -0.00881785 -0.02068331 -1.00506648
  2.46274075 -0.46615531 -0.24117497 -0.24342285 -0.26693271 -0.1058455
 -0.06612829 -0.01079982  0.47226103 -0.44744306  1.52769491 -0.11947101
 -0.03637956 -1.47346684  0.63741496 -0.15066874 -0.12439654 -0.33179062
 -0.08204493 -0.1676198  -0.34899883 -0.06401969 -0.07529085  0.02925687
 -0.02925687]


## Compile, Train and Evaluate the Model

In [116]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(x_train_scaled[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_1_nodes,
                          input_dim=num_input_features,
                          activation='relu')
)


# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_2_nodes,

                          activation='relu')
)


# Output layer
nn.add(
    tf.keras.layers.Dense(units=1,

                          activation='sigmoid')
)

# Check the structure of the model
nn.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 80)                3520      
                                                                 
 dense_13 (Dense)            (None, 30)                2430      
                                                                 
 dense_14 (Dense)            (None, 1)                 31        
                                                                 
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [117]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [118]:
#  Create a callback
import os
from tensorflow.keras.callbacks import ModelCheckpoint
# Define the checkpoint path and filenames
os.makedirs("checkpoints1/",exist_ok=True)
checkpoint_path = "checkpoints1/weights.{epoch:02d}.hdf5"
# Create a callback which saves the weights for every 5 epochs
cp_callback= ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True, period=5)

In [119]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100,callbacks=[cp_callback])

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.5707 - accuracy: 0.7185
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5545 - accuracy: 0.7291
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5514 - accuracy: 0.7303
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7313
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7315
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7331
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7331
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5462 - accuracy: 0.7329
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accura

In [121]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5582 - accuracy: 0.7283 - 960ms/epoch - 4ms/step
Loss: 0.5581536889076233, Accuracy: 0.7282798886299133


In [122]:
# Export our model to HDF5 file
nn.save("alphabetsoup1h.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
